# Generated by Django 2.2 on 2019-04-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='User ID')),
                ('name', models.CharField(max_length=100, verbose_name='Job Name')),
                ('symbol', models.CharField(max_length=30, verbose_name='symbol')),
                ('interval', models.CharField(max_length=30)),
                ('rsi_period', models.IntegerField()),
                ('rsi_value', models.DecimalField(max_digits=20, decimal_places=10)),
                ('bb_period', models.IntegerField()),
                ('bb_std_num', models.IntegerField()),
                ('bb_option', models.CharField(max_length=100)),
                # ('bb_upperband', models.DecimalField(max_digits=20, decimal_places=10)),
                # ('bb_lowerband', models.DecimalField(max_digits=20, decimal_places=10)),
            ],
        ),
    ]
